import type { Metadata } from "next"

import { ReactNode } from "react"

import dynamic from "next/dynamic"

const GlobalWrapper = dynamic(() => import("@/providers/GlobalWrapper"), {
  ssr: false,
})

export const metadata: Metadata = {
  title: "Next + Jotai App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body
        style={{
          background: "#2A2727",
          maxWidth: "100vw",
          overflow: "hidden",
        }}
      >
        <GlobalWrapper>{children}</GlobalWrapper>
      </body>
    </html>
  )
}
